# Generated by Django 5.0.5 on 2024-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linked_in',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../user_image_default_fsrw5b', upload_to='images/'),
        ),
    ]
