# Generated by Django 5.0.5 on 2024-05-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('dogs', 'Dogs'), ('cats', 'Cats'), ('fishes', 'Fishes'), ('birds', 'Birds'), ('horses', 'Horses'), ('training', 'Training'), ('wellness', 'Wellness'), ('adoption', 'Adoption'), ('other', 'Other')], default='Other', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='../default_post_elqjw1', upload_to='images/'),
        ),
    ]
